version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: "sqlite:latest"
    volumes:
      - db-data:/app/db.sqlite

volumes:
  db-data: