# Generated by Django 4.2.5 on 2023-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=50)),
                ('genres', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=50)),
            ],
        ),
    ]
